services:
  nginx:
    image: nginx
    ports:
      - 8080:80

  mongo-0:
    image: mongo:4.4.6-bionic
    container_name: mongo-0
    volumes:
      - mongodb:/data/db:rw
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: codeboxes

volumes:
  mongodb: