services:
    workspace:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ..:/workspace:cached
        command: sleep infinity
    nginx:
        image: nginx
        ports:
            - 8080:80
