services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity

  echoserver:
    image: ealen/echo-server
    environment:
      - "PORT=5000"